<?php include 'header.php'; ?>
<?php include 'navigation.php'; ?>
<?php include 'slider.php'; ?>

<div class="container marketing">

    <div class="row featurette section_blue">
        <div class="col-md-7">
            <h2 class="featurette-heading">About Me. <span class="text-muted">Hi, Im Ben and im a Developer.</span></h2>
            <p class="lead">
                Hi, <br>
                I love to code, programme and explore...
                <br>
                I Love sci-fi books, I love traveling around our wonderful country at the weekends. I love to stay up to
                date with the latest code and science news.
                If you want to learn more about me checkout <a href="blog">My Blog</a>.
            </p>
        </div>
        <div class="col-md-5">
            <img class="featurette-image img-responsive center-block" src="image/ben.jpg" alt="Me (on the left)">
        </div>
    </div>

    <hr class="featurette-divider">

    <div class="row section_red">

        <div class="col-lg-4">
            <img class="img-circle" src="image/work.png" alt="Generic placeholder image" width="140" height="140">
            <h2>My Work</h2>
            <p>This is where I list projects I have worked on and explain a bit about them.</p>
            <p><a class="btn btn-success" href="work.html" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->

        <div class="col-lg-4">
            <img class="img-circle" src="image/cv.jpg" alt="Generic placeholder image" width="140" height="140">
            <h2>My CV</h2>
            <p>My CV, It is avalible for download in PDF format.</p>
            <p><a class="btn btn-success" href="cv.phtml" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->

        <div class="col-lg-4">
            <img class="img-circle" src="image/blog.jpg" alt="Generic placeholder image" width="140" height="140">
            <h2>My Blog</h2>
            <p>My Blog will have post on development and research, what i am doing and developing in my free time.</p>
            <p><a class="btn btn-success" href="blog" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->

    </div><!-- /.row -->
    
    <?php include 'footer.php'; ?>
   